version: '3.9'

services:
  webapp:
    container_name: webapp
    hostname: webserver
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - private-net
  mongo-express:
    container_name: mongoexpress
    hostname: mongoexpress
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: "mongodb://root:toor@mongo:27017/"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
    depends_on:
      - mongo
    networks:
      - private-net
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - private-net
  mongo-seed:
    container_name: mongo-seed
    hostname: mongo-seed
    build:
      context: ./
      dockerfile: deploy/mongo-seed/Dockerfile
      network: host
    networks:
      - private-net
    volumes:
      - "./dump:/dump"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: toor
networks:
  private-net:
