version: '3'

services:
  webapp:
    container_name: webapp
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo2020
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo2020
    ports:
      - "27017:27017"
    volumes:
      - /tmp/Volumes/MongoDB:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
